name: rltobias
favicon: null
layout_spectrum: 0.6224052738398314
typography_spectrum: 0.9961515876930207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6310992720536888
  lightness: 0.15345946792513132
  saturation: 0.30745276901870966
  rhythmicContrast: 0.06460430775769055
purpose: []
